version: "3.5"
services:

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - "./config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"