version: "3.5"
services:

  nginx:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    networks:
      - nginx
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
networks:
  nginx:
    name: nginx