version: "3.5"
services:

  jenkins:
    container_name: jenkins
    image: linhaobin/jenkins-docker
    networks:
      - nginx
    volumes:
      - "/home/jenkins/data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - JAVA_OPTS=-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300 -Xmx350m
    user: root